#!/bin/bash

# GRUB
#sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
#sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mem_sleep_default=s2idle"' /etc/default/grub
sed -i 's/mem_sleep_default=s2idle//g' /etc/default/grub
update-grub

# Flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Recopy HiFi.conf to ucm2
rm /usr/share/alsa/ucm2/Intel/sof-essx8336/HiFi.conf;
cp /usr/share/suspend-then-hibernate/HiFi.conf /usr/share/alsa/ucm2/Intel/sof-essx8336/;
alsaucm reload

# Disable Suspend and replace it with Suspend-then-Hibernate
rm /usr/lib/systemd/system/systemd-suspend.service
ln -s /usr/lib/systemd/system/systemd-suspend-then-hibernate.service /usr/lib/systemd/system/systemd-suspend.service

# Enable Systemd services
systemctl enable juno-pp
systemctl enable juno-kd

# Update initramfs
update-initramfs -u -k all

# Update schemas
glib-compile-schemas /usr/share/glib-2.0/schemas/

# Update systemd
systemd-hwdb update
udevadm trigger -v -p DEVNAME=/dev/iio:device0
udevadm control --reload
udevadm trigger

updatedb

echo "Please restart tablet for updated packages to take effect"

