#!/bin/bash
if [ -f /etc/profile.d/juno-profile.sh ]; then
   rm /etc/profile.d/juno-profile.sh;
fi

if [ -f /etc/udev/rules.d/99-inverted-touchscreen.rules ]; then
   rm /etc/udev/rules.d/99-inverted-touchscreen.rules;
fi
